function expr = SIR(t,in2,in3)
%SIR
%    EXPR = SIR(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-May-2022 14:56:34

I = in2(3,:);
R = in2(1,:);
S = in2(2,:);
param5 = in3(:,1);
param6 = in3(:,2);
t2 = I.*param6;
t3 = I+R+S;
t4 = 1.0./t3;
expr = [t2;-I.*S.*param5.*t4;-I.*t4.*(t2+R.*param6-S.*param5+S.*param6)];
