function expr = siv(t,in2,in3)
%SIV
%    EXPR = SIV(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Jun-2022 16:53:42

I = in2(2,:);
S = in2(1,:);
V = in2(3,:);
param7 = in3(:,1);
param8 = in3(:,2);
param9 = in3(:,3);
param10 = in3(:,4);
param11 = in3(:,5);
t2 = S.*V.*param7;
expr = [S.*(-8.0e-4)+param11-t2;t2-I.*param9;I.*param10-V.*param8];
